services:
  backend:
    build: ./backend
    container_name: collab-backend
    ports:
      - "${BACKEND_PORT:-9134}:${BACKEND_INTERNAL_PORT:-1234}"
    environment:
      - PORT=${BACKEND_INTERNAL_PORT:-1234}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:-}
        VITE_YWS_URL: ${VITE_YWS_URL:-ws://localhost:9134}
    container_name: collab-frontend
    ports:
      - "${FRONTEND_PORT:-8088}:80"
    depends_on:
      - backend
    restart: unless-stopped
