version: "3.9"
services:
  backend:
    build: ./backend
    container_name: collab-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"
    environment:
      - PORT=${BACKEND_INTERNAL_PORT}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_YWS_URL: ${VITE_YWS_URL}
    container_name: collab-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped
